name: Node CI

on:
  push:
    branches: [main]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
          cache: yarn
      - name: Install
        run: yarn --prefer-offline --frozen-lockfile --non-interactive --silent
      - name: Build
        run: yarn build
      - name: Test
        run: yarn test --ci
        env:
          CI: true
      - name: saucelabs
        run: yarn run test:browser
        env:
          CI: true
          SAUCE_USERNAME: ${{ secrets.SAUCE_USERNAME }}
          SAUCE_ACCESS_KEY: ${{ secrets.SAUCE_ACCESS_KEY }}
